const {test}=require('@playwright/test');
const {generateUniqueCode,generateUniqueName}=require('../utils/testData');
const Country=require('../pages/CountryPage'),Currency=require('../pages/CurrencyPage'),Payment=require('../pages/PaymentModesPage'),Delivery=require('../pages/DeliveryModesPage'),Trade=require('../pages/TradeTermsPage'),Sales=require('../pages/SalesTypePage'),Bank=require('../pages/BankPage'),Expense=require('../pages/ExpenseTypePage'),SupplierGroup=require('../pages/SupplierGroupPage'),Supplier=require('../pages/SupplierPage'),Purchase=require('../pages/PurchaseCurrencyRatePage'),SalesRate=require('../pages/SalesCurrencyRatePage'),Parameters=require('../pages/ParametersPage'),Parking=require('../pages/ParkingLocationPage');

test.describe.serial('COMMON MODULE - ALL SCREENS',()=>{
 test('01 Country',async({page})=>{const p=new Country(page),d={code:generateUniqueCode('CT'),name:generateUniqueName('COUNTRY'),nationality:'TEST'};await p.open();await p.add(d);await p.search(d.code);await p.edit(generateUniqueName('CTEDIT'));await p.clear();});
 test('02 Currency',async({page})=>{const p=new Currency(page),d={code:generateUniqueCode('CU'),name:generateUniqueName('CURRENCY')};await p.open();await p.add(d);await p.search(d.code);await p.edit(generateUniqueName('CUREDIT'));await p.clear();});
 test('03 Payment Modes',async({page})=>{const p=new Payment(page),d={code:generateUniqueCode('PM'),name:generateUniqueName('PAYMENT')};await p.open();await p.add(d);await p.search(d.code);await p.edit(generateUniqueName('PAYEDIT'));await p.clear();});
 test('04 Delivery Modes',async({page})=>{const p=new Delivery(page),d={code:generateUniqueCode('DM'),name:generateUniqueName('DELIVERY')};await p.open();await p.add(d);await p.search(d.code);await p.edit(generateUniqueName('DELEDIT'));await p.clear();});
 test('05 Trade Terms',async({page})=>{const p=new Trade(page),d={code:generateUniqueCode('TT'),name:generateUniqueName('TRADE')};await p.open();await p.add(d);await p.search(d.code);await p.edit(generateUniqueName('TREDIT'));await p.clear();});
 test('06 Sales Type',async({page})=>{const p=new Sales(page),d={code:generateUniqueCode('ST'),name:generateUniqueName('SALESTYPE'),displayName:generateUniqueName('SALESNAME')};await p.open();await p.add(d);await p.search(d.code);await p.edit(generateUniqueName('STEDIT'));await p.clear();});
 test('07 Bank',async({page})=>{const p=new Bank(page),d={code:generateUniqueCode('BK'),name:generateUniqueName('BANK')};await p.open();await p.add(d);await p.search(d.code);await p.edit(generateUniqueName('BKEDIT'));await p.clear();});
 test('08 Expense Type',async({page})=>{const p=new Expense(page),d={code:generateUniqueCode('EX'),name:generateUniqueName('EXPENSE')};await p.open();await p.add(d);await p.search(d.code);await p.edit(generateUniqueName('EXEDIT'));await p.clear();});
 test('09 Supplier Group and Supplier',async({page})=>{const g=new SupplierGroup(page),gd={code:generateUniqueCode('SG'),name:generateUniqueName('SUPGROUP')};await g.open();await g.add(gd);await g.search(gd.name);const gu=generateUniqueName('SGEDIT');await g.edit(gu);await g.search(gu);const s=new Supplier(page),sd={code:generateUniqueCode('SP'),name:generateUniqueName('SUPPLIER'),supplierGroupCode:gd.code};await s.open();await s.add(sd);await s.search(sd.name);await s.edit(generateUniqueName('SPEDIT'));await s.clear();await g.clear();});
 test('10 Purchase Currency Rate',async({page})=>{const p=new Purchase(page);await p.open();await p.add({minRate:5,maxRate:6});await p.edit('7');});
 test('11 Sales Currency Rate',async({page})=>{const p=new SalesRate(page);await p.open();await p.add({rate:5});await p.edit('6');});
 test('12 Parameters',async({page})=>{const p=new Parameters(page),d={name:generateUniqueName('PARAM')};await p.open();await p.add(d);await p.search('Miscellaneous');await p.edit(generateUniqueName('PEDIT'));await p.clear();});
 test('13 Parking Location and Slots',async({page})=>{const p=new Parking(page),d={code:generateUniqueCode('PK'),shortName:generateUniqueName('PARK'),name:generateUniqueName('LOCATION')};await p.open();await p.addLocation(d);await p.searchLocation(d.name);await p.addParkingSlot(generateUniqueName('SLOT'));await p.editParkingSlot(generateUniqueName('SLOTEDIT'));await p.clear();});
});